# constants.py
SCREEN_WIDTH = 2560
SCREEN_HEIGHT = 1440

ASTEROID_MIN_RADIUS = 40
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_WIDTH = 2

PLAYER_RADIUS = 20
PLAYER_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

SHOT_RADIUS = 5
SHOT_WIDTH = 2